version: '3'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    user: "${UID}:${GID}"
    environment:
      NEO4J_AUTH: none
      NEO4J_PLUGINS: '["graph-data-science"]'
