openapi: '3.0.3'
info:
  version: '1.0.0'
  title: 'allMusicGrabber API'
  description: Grap data from allmusic

paths:
  /search-artist:
    get:
      summary: Search for an artist by name
      description: Retrieve details about an artist based on the query parameter.
      parameters:
        - name: query
          in: query
          description: The name of the artist to search for.
          required: false
          schema:
            type: string
            example: dismember
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchQuery'
      responses:
        '200':
          description: OK
  /artist/{artistId}:
    parameters:
      - name: artistId
        description: Id of artist in allmusic
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/artistId'
    get:
      summary: Retrieve an artist description
      responses:
        '200':
          description: The artist corresponding to the provided `artistId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artist'
        404:
          description: No artist found for the provided `artistId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /discography/{artistId}:
    get:
      responses:
        '200':
          description: OK
  /related/{artistId}:
    get:
      responses:
        '200':
          description: OK
components:
  schemas:
    artistId:
      description: The unique identifier of an artist
      type: string
    Artist:
      type: object
      required:
        - id
      properties:
        id:
          $ref: '#/components/schemas/artistId'
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
    SearchQuery:
      type: object
      properties:
        query:
          type: string